apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: bb-hpa
 namespace: bb-namespace
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: bb-deployment
 minReplicas: 5
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
