apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bb-pvc
  namespace: bb-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
