apiVersion: v1
kind: PersistentVolume
metadata:
  name: bb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/data/busybox"
