apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-php-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
